
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laftof
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form AdminMain
     */
    boolean eyeButton = true;
    ImageIcon eyeOpen = new ImageIcon(getClass().getResource("/image/eye.png"));        
    ImageIcon eyeClose = new ImageIcon(getClass().getResource("/image/eye_close.png"));  
    
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols(); 
    
    String kodePenjualan = "";
    int statusSearchReport = 0;
    
    public AdminMain(String kode,String namaAdmin) {
        initComponents();        

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);  
    
        lblKasir.setText("Selamat Datang Admin "+namaAdmin+ "("+kode+")");        
        btnEditBarang.setEnabled(false);
        btnHapusBarang.setEnabled(false);
        btnEditKasir.setEnabled(false);
        btnHapusKasir.setEnabled(false);
        labelKodeKasir.setVisible(false);
        kode_kasir.setVisible(false);
        kode_kasir.setEnabled(false);
        load_table_barang();        
        load_table_kasir();                       
        new Thread(){
            public void run(){
                while (true){
                Calendar kal = new GregorianCalendar();
                int tahun = kal.get(Calendar.YEAR);
                int bulan = kal.get(Calendar.MONTH)+1;
                int hari = kal.get(Calendar.DAY_OF_MONTH);
                int jam = kal.get(Calendar.HOUR_OF_DAY);
                int menit = kal.get(Calendar.MINUTE);
                int detik = kal.get(Calendar.SECOND);
                String tanggal = tahun+"-"+bulan+"-"+hari;
                String waktu = jam+":"+menit+":"+detik;
                jLabel13.setText(tanggal +" "+waktu);
                }
            }
        }.start();
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPelanggan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlBarang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnDaftarBarang = new javax.swing.JButton();
        kode_barang = new javax.swing.JTextField();
        satuan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        btnEditBarang = new javax.swing.JButton();
        btnHapusBarang = new javax.swing.JButton();
        btnResetBarang = new javax.swing.JButton();
        harga = new javax.swing.JTextField();
        pnlKasir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelKodeKasir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDaftarKasir = new javax.swing.JButton();
        kode_kasir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat_kasir = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        nama_kasir = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKasir = new javax.swing.JTable();
        btnEditKasir = new javax.swing.JButton();
        btnHapusKasir = new javax.swing.JButton();
        btnDaftar5 = new javax.swing.JButton();
        labelPassword = new javax.swing.JLabel();
        password_kasir = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        telepon_kasir = new javax.swing.JTextField();
        passwordIcon = new javax.swing.JLabel();
        pnlReport = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnDaftarKasir1 = new javax.swing.JButton();
        btnDaftarKasir2 = new javax.swing.JButton();
        scrollReport = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();
        labelPendapatan2 = new javax.swing.JLabel();
        labelPendapatan = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        allReport = new javax.swing.JPanel();
        cardCustomerName = new javax.swing.JPanel();
        searchByName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cardByDay = new javax.swing.JPanel();
        fromReport = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        toReport = new com.toedter.calendar.JDateChooser();
        btnSearch = new javax.swing.JButton();
        pnlDetailReport = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        scrollReport1 = new javax.swing.JScrollPane();
        tableDetailReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kodePenjualanLabel = new javax.swing.JLabel();
        kodePelangganLabel = new javax.swing.JLabel();
        kodeKasirLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        totalBayarLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblKasir = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1390, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(166, 1, 21));

        btnPelanggan.setBackground(new java.awt.Color(245, 169, 169));
        btnPelanggan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnPelanggan.setText("Data Barang");
        btnPelanggan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnPelanggan.setContentAreaFilled(false);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Data Kasir");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Report");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Keluar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        pnlUtama.setLayout(new java.awt.CardLayout());

        pnlBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 51, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(235, 16, 16));
        jLabel10.setText("Data Barang");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Kode Barang");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Satuan");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Harga");

        btnDaftarBarang.setBackground(new java.awt.Color(166, 1, 21));
        btnDaftarBarang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDaftarBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftarBarang.setText("Daftar");
        btnDaftarBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarBarangActionPerformed(evt);
            }
        });

        kode_barang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_barangActionPerformed(evt);
            }
        });

        satuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Nama Barang");

        nama_barang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barangActionPerformed(evt);
            }
        });

        tblBarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblBarang);

        btnEditBarang.setBackground(new java.awt.Color(166, 1, 21));
        btnEditBarang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnEditBarang.setText("Edit");
        btnEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBarangActionPerformed(evt);
            }
        });

        btnHapusBarang.setBackground(new java.awt.Color(166, 1, 21));
        btnHapusBarang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHapusBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusBarang.setText("Hapus");
        btnHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBarangActionPerformed(evt);
            }
        });

        btnResetBarang.setBackground(new java.awt.Color(166, 1, 21));
        btnResetBarang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnResetBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnResetBarang.setText("Reset");
        btnResetBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBarangActionPerformed(evt);
            }
        });

        harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBarangLayout = new javax.swing.GroupLayout(pnlBarang);
        pnlBarang.setLayout(pnlBarangLayout);
        pnlBarangLayout.setHorizontalGroup(
            pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarangLayout.createSequentialGroup()
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel10))
                    .addGroup(pnlBarangLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBarangLayout.createSequentialGroup()
                                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24))
                                .addGap(89, 89, 89)
                                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlBarangLayout.createSequentialGroup()
                                        .addComponent(btnDaftarBarang)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditBarang)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapusBarang)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnResetBarang))))
                            .addGroup(pnlBarangLayout.createSequentialGroup()
                                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarangLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(45, 45, 45))
                                    .addGroup(pnlBarangLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(42, 42, 42)))
                                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nama_barang)
                                    .addComponent(kode_barang, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(410, 410, 410))
        );
        pnlBarangLayout.setVerticalGroup(
            pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(kode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftarBarang)
                    .addComponent(btnEditBarang)
                    .addComponent(btnHapusBarang)
                    .addComponent(btnResetBarang))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlBarang, "pnlBarang");

        pnlKasir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 51, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 16, 16));
        jLabel2.setText("Data Kasir");

        labelKodeKasir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelKodeKasir.setText("Kode Kasir");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Alamat");

        btnDaftarKasir.setBackground(new java.awt.Color(166, 1, 21));
        btnDaftarKasir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDaftarKasir.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftarKasir.setText("Daftar");
        btnDaftarKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarKasirActionPerformed(evt);
            }
        });

        kode_kasir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kode_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_kasirActionPerformed(evt);
            }
        });

        alamat_kasir.setColumns(20);
        alamat_kasir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamat_kasir.setRows(5);
        jScrollPane1.setViewportView(alamat_kasir);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nama");

        nama_kasir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_kasirActionPerformed(evt);
            }
        });

        tblKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKasirMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblKasir);

        btnEditKasir.setBackground(new java.awt.Color(166, 1, 21));
        btnEditKasir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEditKasir.setForeground(new java.awt.Color(255, 255, 255));
        btnEditKasir.setText("Edit");
        btnEditKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKasirActionPerformed(evt);
            }
        });

        btnHapusKasir.setBackground(new java.awt.Color(166, 1, 21));
        btnHapusKasir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHapusKasir.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusKasir.setText("Hapus");
        btnHapusKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKasirActionPerformed(evt);
            }
        });

        btnDaftar5.setBackground(new java.awt.Color(166, 1, 21));
        btnDaftar5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDaftar5.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar5.setText("Reset");
        btnDaftar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftar5ActionPerformed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPassword.setText("Password");

        password_kasir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Telepon");

        telepon_kasir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telepon_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telepon_kasirActionPerformed(evt);
            }
        });

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye.png"))); // NOI18N
        passwordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlKasirLayout = new javax.swing.GroupLayout(pnlKasir);
        pnlKasir.setLayout(pnlKasirLayout);
        pnlKasirLayout.setHorizontalGroup(
            pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKasirLayout.createSequentialGroup()
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKasirLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlKasirLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(65, 65, 65)
                                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlKasirLayout.createSequentialGroup()
                                        .addComponent(btnDaftarKasir)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditKasir)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapusKasir)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDaftar5))
                                    .addComponent(jScrollPane1)))
                            .addGroup(pnlKasirLayout.createSequentialGroup()
                                .addComponent(labelPassword)
                                .addGap(49, 49, 49)
                                .addComponent(password_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passwordIcon))
                            .addGroup(pnlKasirLayout.createSequentialGroup()
                                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlKasirLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(72, 72, 72))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKasirLayout.createSequentialGroup()
                                            .addComponent(labelKodeKasir)
                                            .addGap(40, 40, 40)))
                                    .addGroup(pnlKasirLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(58, 58, 58)))
                                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama_kasir, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(kode_kasir)
                                    .addComponent(telepon_kasir)))))
                    .addGroup(pnlKasirLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel2)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        pnlKasirLayout.setVerticalGroup(
            pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeKasir)
                    .addComponent(kode_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nama_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telepon_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPassword)
                        .addComponent(password_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftarKasir)
                    .addComponent(btnEditKasir)
                    .addComponent(btnHapusKasir)
                    .addComponent(btnDaftar5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlKasir, "pnlKasir");

        pnlReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 51, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 16, 16));
        jLabel3.setText("Report");

        btnDaftarKasir1.setBackground(new java.awt.Color(166, 1, 21));
        btnDaftarKasir1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDaftarKasir1.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftarKasir1.setText("Report By Day");
        btnDaftarKasir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarKasir1ActionPerformed(evt);
            }
        });

        btnDaftarKasir2.setBackground(new java.awt.Color(166, 1, 21));
        btnDaftarKasir2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDaftarKasir2.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftarKasir2.setText("Report By Customer Name");
        btnDaftarKasir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarKasir2ActionPerformed(evt);
            }
        });

        tableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReportMouseClicked(evt);
            }
        });
        scrollReport.setViewportView(tableReport);

        labelPendapatan2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPendapatan2.setForeground(new java.awt.Color(166, 1, 21));
        labelPendapatan2.setText("Rp. 200.000,00");

        labelPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPendapatan.setText("Total Pendapatan :");

        btnDetails.setBackground(new java.awt.Color(166, 1, 21));
        btnDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnDetails.setText("Go To Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        allReport.setBackground(new java.awt.Color(255, 255, 255));
        allReport.setLayout(new java.awt.CardLayout());

        cardCustomerName.setBackground(new java.awt.Color(255, 255, 255));

        searchByName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Customer Name");

        javax.swing.GroupLayout cardCustomerNameLayout = new javax.swing.GroupLayout(cardCustomerName);
        cardCustomerName.setLayout(cardCustomerNameLayout);
        cardCustomerNameLayout.setHorizontalGroup(
            cardCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCustomerNameLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(cardCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardCustomerNameLayout.createSequentialGroup()
                        .addComponent(searchByName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardCustomerNameLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(60, 60, 60))))
        );
        cardCustomerNameLayout.setVerticalGroup(
            cardCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCustomerNameLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByName, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        allReport.add(cardCustomerName, "cardCustomerName");

        cardByDay.setBackground(new java.awt.Color(255, 255, 255));

        fromReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("From");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("To");

        toReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout cardByDayLayout = new javax.swing.GroupLayout(cardByDay);
        cardByDay.setLayout(cardByDayLayout);
        cardByDayLayout.setHorizontalGroup(
            cardByDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardByDayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardByDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromReport, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardByDayLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(cardByDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardByDayLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(78, 78, 78)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardByDayLayout.setVerticalGroup(
            cardByDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardByDayLayout.createSequentialGroup()
                .addGroup(cardByDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardByDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromReport, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(toReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        allReport.add(cardByDay, "cardByDay");

        btnSearch.setBackground(new java.awt.Color(166, 1, 21));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jLabel3)
                .addContainerGap(444, Short.MAX_VALUE))
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addComponent(scrollReport, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlReportLayout.createSequentialGroup()
                                .addComponent(btnDaftarKasir1)
                                .addGap(18, 18, 18)
                                .addComponent(btnDaftarKasir2))
                            .addComponent(allReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReportLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(labelPendapatan))
                            .addGroup(pnlReportLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)))
                        .addGap(18, 18, 18)
                        .addComponent(labelPendapatan2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetails)
                .addGap(156, 156, 156))
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftarKasir1)
                    .addComponent(btnDaftarKasir2)
                    .addComponent(labelPendapatan)
                    .addComponent(labelPendapatan2))
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(allReport, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollReport, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pnlUtama.add(pnlReport, "pnlReport");

        pnlDetailReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 51, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 16, 16));
        jLabel4.setText("Detail Report");

        tableDetailReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollReport1.setViewportView(tableDetailReport);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Kode Penjualan :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Kode Kasir :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Kode Pelanggan :");

        kodePenjualanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kodePenjualanLabel.setForeground(new java.awt.Color(166, 1, 21));
        kodePenjualanLabel.setText("123");

        kodePelangganLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kodePelangganLabel.setForeground(new java.awt.Color(166, 1, 21));
        kodePelangganLabel.setText("123");

        kodeKasirLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kodeKasirLabel.setForeground(new java.awt.Color(166, 1, 21));
        kodeKasirLabel.setText("123");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Tanggal :");

        tanggalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggalLabel.setForeground(new java.awt.Color(166, 1, 21));
        tanggalLabel.setText("123");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Total Harga :");

        totalHargaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalHargaLabel.setForeground(new java.awt.Color(166, 1, 21));
        totalHargaLabel.setText("123");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Total Bayar :");

        totalBayarLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalBayarLabel.setForeground(new java.awt.Color(166, 1, 21));
        totalBayarLabel.setText("123");

        jButton1.setBackground(new java.awt.Color(166, 1, 21));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetailReportLayout = new javax.swing.GroupLayout(pnlDetailReport);
        pnlDetailReport.setLayout(pnlDetailReportLayout);
        pnlDetailReportLayout.setHorizontalGroup(
            pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailReportLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailReportLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(366, 366, 366))
                    .addGroup(pnlDetailReportLayout.createSequentialGroup()
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDetailReportLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailReportLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18))
                                        .addGroup(pnlDetailReportLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(24, 24, 24)))
                                    .addGroup(pnlDetailReportLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(56, 56, 56)))
                                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kodeKasirLabel)
                                    .addComponent(kodePenjualanLabel)
                                    .addComponent(kodePelangganLabel))
                                .addGap(196, 196, 196)
                                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlDetailReportLayout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(24, 24, 24)))
                                    .addComponent(jLabel17))
                                .addGap(41, 41, 41)
                                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalHargaLabel)
                                    .addComponent(tanggalLabel)
                                    .addComponent(totalBayarLabel))))
                        .addContainerGap(119, Short.MAX_VALUE))))
        );
        pnlDetailReportLayout.setVerticalGroup(
            pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailReportLayout.createSequentialGroup()
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kodePenjualanLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kodeKasirLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kodePelangganLabel)))
                    .addGroup(pnlDetailReportLayout.createSequentialGroup()
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tanggalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(totalHargaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetailReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(totalBayarLabel))))
                .addGap(28, 28, 28)
                .addComponent(scrollReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlDetailReport, "pnlDetailReport");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(995, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 228, Short.MAX_VALUE)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1220, 630));

        jPanel4.setBackground(new java.awt.Color(235, 16, 16));

        lblKasir.setBackground(new java.awt.Color(235, 16, 16));
        lblKasir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblKasir.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resetKasir();
        load_table_kasir();        
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlKasir");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        searchByName.setVisible(false);
        btnSearch.setVisible(false);
        scrollReport.setVisible(false);
        labelPendapatan.setVisible(false);
        labelPendapatan2.setVisible(false);
        btnDetails.setVisible(false);
        allReport.setVisible(false);
        statusSearchReport = 0;
        searchByName.setText("");
        fromReport.setCalendar(null);
        toReport.setCalendar(null);
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlReport");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        resetBarang();
        load_table_barang();        
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlBarang");
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnDaftarBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarBarangActionPerformed
String sql = "select COUNT(1) from ms_barang where kode_barang = '"+kode_barang.getText()+"'";
        
        int countBarang = 0;
        try{
            ResultSet rs = Koneksi.executeQuery(sql);
             if(rs.next()){
                    String query = rs.getString(1);
                    countBarang = Integer.parseInt(query);                                         
                }
        }catch (SQLException ex){
             Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
         }
         
        if (countBarang > 0) {
                     JOptionPane.showMessageDialog(this, "Kode Barang "+kode_barang.getText()+" Already Exist","ERROR", JOptionPane.ERROR_MESSAGE);
         }else if ("".equals(kode_barang.getText()) || "".equals(nama_barang.getText()) ||
                "".equals(satuan.getText()) || "".equals(harga.getText())){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            
            String SQL = "INSERT INTO ms_barang "
                    + "VALUES ('"+kode_barang.getText()+"','"+nama_barang.getText()+"','"+satuan.getText()+
                    "','"+harga.getText()+"')";
             int status = Koneksi.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan ", "sukses",
                        JOptionPane.INFORMATION_MESSAGE);  
                resetBarang();
                load_table_barang();  
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan ", "Gagal",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDaftarBarangActionPerformed

    private void kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_barangActionPerformed

    private void satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanActionPerformed

    private void nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barangActionPerformed

    private void btnEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBarangActionPerformed
        if ("".equals(kode_barang.getText()) || "".equals(nama_barang.getText()) ||
                "".equals(satuan.getText()) || "".equals(harga.getText())){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            String sql = "Update ms_barang set kode_barang = '"+kode_barang.getText()+"', nama_barang = '" +nama_barang.getText()+
                    "',satuan ='"+satuan.getText()+"',harga='"+harga.getText()+"' where kode_barang = '"+kode_barang.getText()+"'";
             int status = Koneksi.execute(sql);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil diubah ", "sukses",
                        JOptionPane.INFORMATION_MESSAGE);  
                resetBarang();                
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diubah ", "Gagal",
                        JOptionPane.ERROR_MESSAGE);
            }            
        }
        load_table_barang();  
    }//GEN-LAST:event_btnEditBarangActionPerformed

    private void btnHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBarangActionPerformed
        String sql = "delete from ms_barang where kode_barang='"+kode_barang.getText()+"'";
             int status = Koneksi.execute(sql);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus ", "sukses",
                        JOptionPane.INFORMATION_MESSAGE);  
                resetBarang();                
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus ", "Gagal",
                        JOptionPane.ERROR_MESSAGE);
            }
            load_table_barang();
    }//GEN-LAST:event_btnHapusBarangActionPerformed

    private void btnResetBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBarangActionPerformed
        resetBarang();
    }//GEN-LAST:event_btnResetBarangActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        int baris = tblBarang.rowAtPoint(evt.getPoint());
        
        String txtKodeBarang = tblBarang.getValueAt(baris, 1).toString();
        kode_barang.setText(txtKodeBarang);
        
        String txtNamaBarang = tblBarang.getValueAt(baris, 2).toString();
        nama_barang.setText(txtNamaBarang);
        
        String txtSatuan =tblBarang.getValueAt(baris, 3).toString();
        satuan.setText(txtSatuan);
        
        String txtHarga = tblBarang.getValueAt(baris, 4).toString();
        harga.setText(txtHarga);        
        
        btnEditBarang.setEnabled(true);
        btnHapusBarang.setEnabled(true);
        kode_barang.setEnabled(false);
        btnDaftarBarang.setEnabled(false);        
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnDaftar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftar5ActionPerformed
        resetKasir();
    }//GEN-LAST:event_btnDaftar5ActionPerformed

    private void btnHapusKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKasirActionPerformed
        String sql = "delete from ms_kasir where kode_kasir='"+kode_kasir.getText()+"'";
        int status = Koneksi.execute(sql);
        if (status == 1){
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus ", "sukses",
                JOptionPane.INFORMATION_MESSAGE);
            resetKasir();
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal dihapus ", "Gagal",
                JOptionPane.ERROR_MESSAGE);
        }
        load_table_kasir();
    }//GEN-LAST:event_btnHapusKasirActionPerformed

    private void btnEditKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKasirActionPerformed
        if ("".equals(nama_kasir.getText()) || "".equals(telepon_kasir.getText()) ||
                "".equals(alamat_kasir.getText()) || "".equals(kode_kasir.getText())){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            String sql = "Update ms_kasir set nama_kasir = '" +nama_kasir.getText()+"',telepon ='"+telepon_kasir.getText()+
                    "',alamat='"+alamat_kasir.getText()+"' where kode_kasir = '"+kode_kasir.getText()+"'";
             int status = Koneksi.execute(sql);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil diubah ", "sukses",
                        JOptionPane.INFORMATION_MESSAGE);  
                resetKasir();                
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diubah ", "Gagal",
                        JOptionPane.ERROR_MESSAGE);
            }            
        }
        load_table_kasir();  
    }//GEN-LAST:event_btnEditKasirActionPerformed

    private void tblKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKasirMouseClicked
        int baris = tblKasir.rowAtPoint(evt.getPoint());

        String txtKodeKasir = tblKasir.getValueAt(baris, 1).toString();
        kode_kasir.setText(txtKodeKasir);

        String txtNamaKasir = tblKasir.getValueAt(baris, 2).toString();
        nama_kasir.setText(txtNamaKasir);

        String txtTelepon = tblKasir.getValueAt(baris, 3).toString();
        telepon_kasir.setText(txtTelepon);

        String txtAlamat = tblKasir.getValueAt(baris, 4).toString();
        alamat_kasir.setText(txtAlamat);

        password_kasir.setVisible(false);
        labelPassword.setVisible(false);

        btnEditKasir.setEnabled(true);
        btnHapusKasir.setEnabled(true);
        kode_kasir.setVisible(true);
        labelKodeKasir.setVisible(true);
        btnDaftarKasir.setEnabled(false);
        passwordIcon.setVisible(false);
    }//GEN-LAST:event_tblKasirMouseClicked

    private void nama_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_kasirActionPerformed

    private void kode_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_kasirActionPerformed

    private void btnDaftarKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarKasirActionPerformed
        String newKodeKasir ="KSR_001";
        String sql = "select kode_kasir from ms_kasir where kode_kasir like '%KSR%' order by kode_kasir desc limit 1;";

        try{
            ResultSet rs = Koneksi.executeQuery(sql);
            if(rs.next()){
                String kodeKasir = rs.getString(1);
                String[] arrKode = kodeKasir.split("KSR_", 2);

                if (arrKode.length == 2) {
                    int KK = Integer.parseInt(arrKode[1]);
                    KK ++;
                    newKodeKasir = "KSR_"+String.format("%1$" + 3 + "s", String.valueOf(KK)).replace(' ', '0');
                }
            }
        }catch (SQLException ex){
            Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        if ("".equals(nama_kasir.getText()) || "".equals(telepon_kasir.getText()) || "".equals(alamat_kasir.getText())
            || "".equals(password_kasir.getText())){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR", JOptionPane.ERROR_MESSAGE);
        }else{

            String encPassword = null;
            try {
                MessageDigest md = MessageDigest.getInstance("MD5");
                byte[] hash = md.digest(password_kasir.getText().getBytes());

                //converting byte array to Hexadecimal String
                StringBuilder sb = new StringBuilder(2*hash.length);
                for(byte b : hash){
                    sb.append(String.format("%02x", b&0xff));
                }

                encPassword = sb.toString();

            } catch (NoSuchAlgorithmException ex) { }

            SimpleDateFormat tanggalMasuk = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();

            String SQL = "INSERT INTO ms_kasir "
            + "VALUES ('"+newKodeKasir+"','"+nama_kasir.getText()+"','"+telepon_kasir.getText()+
            "','"+alamat_kasir.getText()+"','"+tanggalMasuk.format(date)+"','"+encPassword+"')";
            int status = Koneksi.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan ", "sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                resetKasir();
                load_table_kasir();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan ", "Gagal",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDaftarKasirActionPerformed

    private void telepon_kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telepon_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telepon_kasirActionPerformed

    private void passwordIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordIconMouseClicked
        if (eyeButton) {
            eyeButton = false;
            passwordIcon.setIcon(eyeClose);
            password_kasir.setEchoChar((char)0);
        }else{
            eyeButton = true;
            passwordIcon.setIcon(eyeOpen);
            password_kasir.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordIconMouseClicked

    private void btnDaftarKasir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarKasir1ActionPerformed
        searchByName.setVisible(false);
        btnSearch.setVisible(true);
        scrollReport.setVisible(false);
        btnDetails.setVisible(false);
        allReport.setVisible(true);
        CardLayout clayout = (CardLayout) allReport.getLayout();
        clayout.show(allReport, "cardByDay");
        statusSearchReport = 1;               
    }//GEN-LAST:event_btnDaftarKasir1ActionPerformed

    private void btnDaftarKasir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarKasir2ActionPerformed
        searchByName.setVisible(true);
        btnSearch.setVisible(true);
        scrollReport.setVisible(false);
        labelPendapatan.setVisible(false);
        labelPendapatan2.setVisible(false);
        btnDetails.setVisible(false);
        CardLayout clayout = (CardLayout) allReport.getLayout();
        clayout.show(allReport, "cardCustomerName");
        statusSearchReport = 2;
    }//GEN-LAST:event_btnDaftarKasir2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String[] judul = {"No", "Kode Penjualan", "Kode Kasir", "Kode Pelanggan", "Tanggal", "Total Harga", "Total Bayar"};
        
        DefaultTableModel model = new DefaultTableModel(judul, 0){

    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }
};               
        Date from = fromReport.getDate();
        Date to = toReport.getDate();
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");               
        
        if (statusSearchReport == 2){
            if ("".equals(searchByName.getText())){
                JOptionPane.showMessageDialog(this, "Harap masukkan nama Customer","ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }            
        }else{
            if (from == null){
            JOptionPane.showMessageDialog(this, "Harap masukkan Tanggal Awal Pencarian","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
            }else if (to == null){
            JOptionPane.showMessageDialog(this, "Harap masukkan Tanggal Akhir Pencarian","ERROR", JOptionPane.ERROR_MESSAGE);
            return;
            }else if (from.getTime() > to.getTime()){
            JOptionPane.showMessageDialog(this, "Tanggal Akhir Pencarian Harus Lebih Besar Atau Sama Dengan Tanggal Awal Pencarian",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }        
        
            try{
                int no=1;
                System.out.println(format1.format(from));
                System.out.println(format1.format(to));
                if (statusSearchReport == 1) {
                    String sql = "select kode_penjualan, kode_kasir, kode_pelanggan, tanggal, COALESCE(total, 0), COALESCE(bayar, 0) from tb_penjualan"
                    + " WHERE DATE_FORMAT(tanggal, '%Y-%m-%d') BETWEEN '"+format1.format(from)+"' AND '"+format1.format(to)+"' "
                            + "ORDER BY tanggal DESC";            
            java.sql.ResultSet res = Koneksi.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),
                kursIndonesia.format(Double.parseDouble(res.getString(5))), kursIndonesia.format(Double.parseDouble(res.getString(6)))});
            }
            
            String sql2 = "select COALESCE(SUM(total), 0) from tb_penjualan WHERE DATE_FORMAT(tanggal, '%Y-%m-%d') BETWEEN '"+format1.format(from)+"' "
                    + "AND '"+format1.format(to)+"' ";            
            java.sql.ResultSet res2 = Koneksi.executeQuery(sql2);
            while(res2.next()){                              
                labelPendapatan2.setText(kursIndonesia.format(Double.parseDouble(res2.getString(1))));                
            }
            labelPendapatan.setVisible(true);
            labelPendapatan2.setVisible(true);            
                }else{
                    String sql = "select tp.kode_penjualan, tp.kode_kasir, tp.kode_pelanggan, tp.tanggal, COALESCE(tp.total, 0), "
                    + "COALESCE(tp.bayar, 0), mp.nama_pelanggan from tb_penjualan tp LEFT JOIN ms_pelanggan mp on "
                    + "tp.kode_pelanggan = mp.kode_pelanggan WHERE mp.nama_pelanggan like '%"+searchByName.getText()+"%' "
                    + "ORDER BY tp.tanggal DESC";            
            java.sql.ResultSet res = Koneksi.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),
                kursIndonesia.format(Double.parseDouble(res.getString(5))), 
                kursIndonesia.format(Double.parseDouble(res.getString(6)))});
            }
                        
            labelPendapatan.setVisible(false);
            labelPendapatan2.setVisible(false);            
                }                        
                tableReport.setModel(model);
            scrollReport.setVisible(true);
        }
        catch(Exception e){
            System.err.println(e);}            
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        String[] judul = {"No", "Kode Barang", "Nama Barang", "Harga", "Jumlah", "Total"};
        
        DefaultTableModel model = new DefaultTableModel(judul, 0){

    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }
};               
        
        try{
            int no=1;
            String sql = "select dp.*, b.nama_barang from tb_detail_penjualan dp LEFT JOIN ms_barang b on dp.kode_barang = "
                    + "b.kode_barang WHERE dp.kode_penjualan = '"+kodePenjualan+"'";            
            java.sql.ResultSet res = Koneksi.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {no++,res.getString(2), res.getString(6), 
                    kursIndonesia.format(Double.parseDouble(res.getString(3))), res.getString(4), 
                    kursIndonesia.format(Double.parseDouble(res.getString(5)))});
            }  
            tableDetailReport.setModel(model);
        }
        catch(Exception e){
            System.err.println(e);}
        
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlDetailReport");
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void tableReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReportMouseClicked
        btnDetails.setVisible(true);
        int baris = tableReport.rowAtPoint(evt.getPoint());
        kodePenjualan = tableReport.getValueAt(baris, 1).toString();
        kodePenjualanLabel.setText(kodePenjualan);
        
        String kodeKasir = tableReport.getValueAt(baris, 2).toString();
        kodeKasirLabel.setText(kodeKasir);
        
        String kodePelanggan = tableReport.getValueAt(baris, 3).toString();
        kodePelangganLabel.setText(kodePelanggan);
        
        String tanggal = tableReport.getValueAt(baris, 4).toString();
        tanggalLabel.setText(tanggal);
        
        String totalHarga = tableReport.getValueAt(baris, 5).toString();
        totalHargaLabel.setText(totalHarga);
        
        String totalBayar = tableReport.getValueAt(baris, 6).toString();
        totalBayarLabel.setText(totalBayar);
    }//GEN-LAST:event_tableReportMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlReport");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_kasir;
    private javax.swing.JPanel allReport;
    private javax.swing.JButton btnDaftar5;
    private javax.swing.JButton btnDaftarBarang;
    private javax.swing.JButton btnDaftarKasir;
    private javax.swing.JButton btnDaftarKasir1;
    private javax.swing.JButton btnDaftarKasir2;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnEditBarang;
    private javax.swing.JButton btnEditKasir;
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnHapusKasir;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnResetBarang;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel cardByDay;
    private javax.swing.JPanel cardCustomerName;
    private com.toedter.calendar.JDateChooser fromReport;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel kodeKasirLabel;
    private javax.swing.JLabel kodePelangganLabel;
    private javax.swing.JLabel kodePenjualanLabel;
    private javax.swing.JTextField kode_barang;
    private javax.swing.JTextField kode_kasir;
    private javax.swing.JLabel labelKodeKasir;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPendapatan;
    private javax.swing.JLabel labelPendapatan2;
    private javax.swing.JLabel lblKasir;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_kasir;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JPasswordField password_kasir;
    private javax.swing.JPanel pnlBarang;
    private javax.swing.JPanel pnlDetailReport;
    private javax.swing.JPanel pnlKasir;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTextField satuan;
    private javax.swing.JScrollPane scrollReport;
    private javax.swing.JScrollPane scrollReport1;
    private javax.swing.JTextField searchByName;
    private javax.swing.JTable tableDetailReport;
    private javax.swing.JTable tableReport;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblKasir;
    private javax.swing.JTextField telepon_kasir;
    private com.toedter.calendar.JDateChooser toReport;
    private javax.swing.JLabel totalBayarLabel;
    private javax.swing.JLabel totalHargaLabel;
    // End of variables declaration//GEN-END:variables

    private void load_table_barang() {
        String[] judul = {"No", "Kode Barang", "Nama Barang", "Satuan", "Harga"};
        
        DefaultTableModel model = new DefaultTableModel(judul, 0){

    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }
};               
        
        try{
            int no=1;
            String sql = "select * from ms_barang";            
            java.sql.ResultSet res = Koneksi.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            tblBarang.setModel(model);
        }
        catch(Exception e){}
    }

    private void resetBarang() {
        kode_barang.setText("");
        nama_barang.setText("");
        satuan.setText("");
        harga.setText("");
        btnEditBarang.setEnabled(false);
        btnHapusBarang.setEnabled(false);
        kode_barang.setEnabled(true);
        btnDaftarBarang.setEnabled(true);
    }

    private void resetKasir() {
        kode_kasir.setText("");
        nama_kasir.setText("");
        telepon_kasir.setText("");
        password_kasir.setText("");
        alamat_kasir.setText("");
        btnEditKasir.setEnabled(false);
        btnHapusKasir.setEnabled(false);
        kode_kasir.setVisible(false);
        labelKodeKasir.setVisible(false);
        password_kasir.setVisible(true);
        labelPassword.setVisible(true);
        btnDaftarKasir.setEnabled(true);
        passwordIcon.setVisible(true);
        eyeButton = true;
        passwordIcon.setIcon(eyeOpen);
        password_kasir.setEchoChar('*');
    }

    private String byteArrToString(byte[] b) {
        StringBuilder sb = new StringBuilder(b.length * 2);
        for (int i = 0; i < b.length; i++) {
            int j = b[i] & 0xff;
            if (j < 16) {
                sb.append('0');
            }
            sb.append(Integer.toHexString(j));
        }
        String res = sb.toString();
        return res.toUpperCase();
    }

    private void load_table_kasir() {
        String[] judul = {"No", "Kode Kasir", "Nama Kasir", "Telepon", "Alamat", "Tanggal Masuk"};
        
        DefaultTableModel model = new DefaultTableModel(judul, 0){

    @Override
    public boolean isCellEditable(int row, int column) {
       return false;
    }
};               
        
        try{
            int no=1;
            String sql = "select * from ms_kasir WHERE kode_kasir like '%KSR%'";            
            java.sql.ResultSet res = Koneksi.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[] {no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),
                res.getString(5)});
            }
            tblKasir.setModel(model);            
        }
        catch(Exception e){}
    }
}
