
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laftof
 */
public class KasirMain extends javax.swing.JFrame {
int a = 0;
String idpelanggan;
String namabarang;
String kode ;
String kodebarang;
String namakasir;
String kodepenjualan;
String[] kolom = {"NamaBarang","Harga","JumlahBeli"};
DefaultTableModel dtm = new DefaultTableModel(null,kolom);
String[] kolom1 = {"NamaBarang","Harga","JumlahBeli","SubTotal"};
DefaultTableModel dftr = new DefaultTableModel(null,kolom1);
String[] kolom2 = {"NO","Nama Barang","Harga"};
DefaultTableModel dft = new DefaultTableModel(null,kolom2);
String[] kolom3 = {"Id","Nama","Alamat"};
DefaultTableModel plg = new DefaultTableModel(null,kolom3);
String kembali="";
String ongk="";
    /**
     * Creates new form KasirMain
     */
    public KasirMain(String kode,String namakasir) {
        initComponents();
//        setExtendedState(KasirMain.MAXIMIZED_BOTH); 
//        this.kode = kode;
//        this.namakasir = namakasir;
        this.kode=kode;
        this.namakasir=namakasir;

        lblKasir.setText("Selamat Datang kasir "+namakasir+ "  ("+kode+")");
        tblBarang.setModel(dtm);
        tblDaftar.setModel(dftr);
        tblCari.setModel(dft);
        tblPlg.setModel(plg);
        new Thread(){
            public void run(){
                while (true){
                Calendar kal = new GregorianCalendar();
                int tahun = kal.get(Calendar.YEAR);
                int bulan = kal.get(Calendar.MONTH)+1;
                int hari = kal.get(Calendar.DAY_OF_MONTH);
                int jam = kal.get(Calendar.HOUR_OF_DAY);
                int menit = kal.get(Calendar.MINUTE);
                int detik = kal.get(Calendar.SECOND);
                String tanggal = tahun+"-"+bulan+"-"+hari;
                String waktu = jam+":"+menit+":"+detik;
                jLabel13.setText(tanggal +" // "+waktu);
                }
            }
        }.start();
    }
    
    public String getkodepenjualan(){
        String sql = "select kode_penjualan from tb_penjualan order by kode_penjualan desc limit 1;";
        
                try{
                    ResultSet rs = Koneksi.executeQuery(sql);
                     if(rs.next()){
                            kodepenjualan = rs.getString(1);
                            int kp= Integer.parseInt(kodepenjualan);
                             kp ++;
                             kodepenjualan = String.valueOf(kp);
                        }else{
                            kodepenjualan ="1";
                        }
                }catch (SQLException ex){
                     Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
                 }
                return kodepenjualan;
    }
    
    public void kosong(){
        txtNama.setText("");
        lblNma.setText("");
        lblPlg.setText("");
        dftNama.setText("");
        dftTlf.setText("");
        dftAlamat.setText("");
        dftKeterangan.setText("");
        txtBarang.setText("");
        labelnm.setText("");
        labelid.setText("");
        txtTotal.setText("");
        txtBay.setText("");
        txtKembalian.setText("");
        dftr = new DefaultTableModel(null,kolom1);
        dtm = new DefaultTableModel(null,kolom);
        plg = new DefaultTableModel(null,kolom3);
        tblBarang.setModel(dtm);
        tblDaftar.setModel(dftr);
        tblPlg.setModel(plg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPelanggan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlPelanggan = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPlg = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        btnMulai = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblNma = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblPlg = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnDaftar = new javax.swing.JButton();
        pnlDaftar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDaftar2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        dftKeterangan = new javax.swing.JTextField();
        dftNama = new javax.swing.JTextField();
        dftTlf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dftAlamat = new javax.swing.JTextArea();
        btnOke = new javax.swing.JButton();
        pnlBeli = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtBarang = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCari = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtj = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbln = new javax.swing.JLabel();
        pnlDaftarBelanja = new javax.swing.JPanel();
        labelnm = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDaftar = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtBay = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblKasir = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1390, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(166, 1, 21));

        btnPelanggan.setBackground(new java.awt.Color(245, 169, 169));
        btnPelanggan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnPelanggan.setText("Pelanggan");
        btnPelanggan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnPelanggan.setContentAreaFilled(false);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Beli Barang");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Daftar Belanja");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Keluar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pnlUtama.setLayout(new java.awt.CardLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Pelanggan");

        jLabel8.setText("Nama");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Pelanggan"));
        jPanel12.setLayout(new java.awt.CardLayout());

        tblPlg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlgMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblPlg);

        jPanel12.add(jScrollPane5, "card2");

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMulai.setText("MULAI");
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });
        jPanel13.add(btnMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 121, 112, 40));

        jLabel9.setText("Nama");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 32, -1, -1));

        jLabel10.setText("Id Pelanggan");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 92, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.CardLayout());

        lblNma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel14.add(lblNma, "card2");

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 16, 174, 36));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.CardLayout());

        lblPlg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel15.add(lblPlg, "card2");

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 80, 174, 32));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari))
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );

        jPanel9.setBackground(new java.awt.Color(235, 16, 16));

        btnDaftar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setText("Buat Akun Pelanggan");
        btnDaftar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnDaftar.setContentAreaFilled(false);
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPelangganLayout = new javax.swing.GroupLayout(pnlPelanggan);
        pnlPelanggan.setLayout(pnlPelangganLayout);
        pnlPelangganLayout.setHorizontalGroup(
            pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPelangganLayout.setVerticalGroup(
            pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPelangganLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlUtama.add(pnlPelanggan, "pnlPelanggan");

        pnlDaftar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 51, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 16, 16));
        jLabel2.setText("Daftar Menjadi Member Turen Indah");

        jLabel3.setText("Nama");

        jLabel4.setText("Telepon");

        jLabel5.setText("Alamat");

        btnDaftar2.setText("Daftar");
        btnDaftar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftar2ActionPerformed(evt);
            }
        });

        dftKeterangan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dftKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dftKeteranganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(dftKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dftKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dftNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dftNamaActionPerformed(evt);
            }
        });

        dftAlamat.setColumns(20);
        dftAlamat.setRows(5);
        jScrollPane1.setViewportView(dftAlamat);

        btnOke.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnOke.setText("OK");
        btnOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarLayout = new javax.swing.GroupLayout(pnlDaftar);
        pnlDaftar.setLayout(pnlDaftarLayout);
        pnlDaftarLayout.setHorizontalGroup(
            pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarLayout.createSequentialGroup()
                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaftarLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDaftarLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDaftarLayout.createSequentialGroup()
                                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dftTlf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                        .addComponent(dftNama, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(btnDaftar2)))
                    .addGroup(pnlDaftarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOke, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlDaftarLayout.setVerticalGroup(
            pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dftNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dftTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDaftar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(pnlDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDaftarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnOke, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
        );

        pnlUtama.add(pnlDaftar, "pnlDaftar");

        pnlBeli.setBackground(new java.awt.Color(255, 255, 255));
        pnlBeli.setPreferredSize(new java.awt.Dimension(1019, 757));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(235, 16, 16));
        jLabel11.setText("Cari Barang");

        txtBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarangActionPerformed(evt);
            }
        });

        btnCariBarang.setText("Cari");
        btnCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(235, 16, 16));
        jLabel12.setText("Harga satuan ");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(235, 16, 16));
        jLabel14.setText("Jumlah beli");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new java.awt.CardLayout());

        tblCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCariMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCari);

        jPanel3.add(jScrollPane4, "card2");

        jPanel8.setBackground(new java.awt.Color(255, 0, 23));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.setCellSelectionEnabled(true);
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBarang);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));

        jLabel1.setText("Nama");

        jLabel6.setText("Jumlah Beli");

        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbln.setBackground(new java.awt.Color(153, 153, 255));
        lbln.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtj, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(lbln, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbln, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addContainerGap(448, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnHapus)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah)
                                    .addComponent(txtHarga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCariBarang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCariBarang)
                            .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(btnTambah))))
                .addGap(43, 43, 43)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBeliLayout = new javax.swing.GroupLayout(pnlBeli);
        pnlBeli.setLayout(pnlBeliLayout);
        pnlBeliLayout.setHorizontalGroup(
            pnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBeliLayout.setVerticalGroup(
            pnlBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBeliLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlBeli, "pnlBeli");

        pnlDaftarBelanja.setBackground(new java.awt.Color(255, 255, 255));

        labelnm.setBackground(new java.awt.Color(235, 16, 16));
        labelnm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelnm.setForeground(new java.awt.Color(235, 16, 16));
        labelnm.setText("Nama Pelanggan");

        labelid.setBackground(new java.awt.Color(235, 16, 16));
        labelid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelid.setForeground(new java.awt.Color(235, 16, 16));
        labelid.setText("Id Pelanggan");

        jPanel10.setLayout(new java.awt.CardLayout());

        tblDaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDaftar);

        jPanel10.add(jScrollPane3, "card2");

        jLabel18.setBackground(new java.awt.Color(235, 16, 16));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(235, 16, 16));
        jLabel18.setText("Total");

        jButton14.setText("SELESAI");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(235, 16, 16));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(235, 16, 16));
        jLabel19.setText("Bayar");

        jLabel20.setBackground(new java.awt.Color(235, 16, 16));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(235, 16, 16));
        jLabel20.setText("Kembalian");

        jButton15.setText("EDIT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaftarBelanjaLayout = new javax.swing.GroupLayout(pnlDaftarBelanja);
        pnlDaftarBelanja.setLayout(pnlDaftarBelanjaLayout);
        pnlDaftarBelanjaLayout.setHorizontalGroup(
            pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDaftarBelanjaLayout.createSequentialGroup()
                .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(114, 114, 114)
                .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtBay)
                    .addComponent(txtKembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(pnlDaftarBelanjaLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(labelnm, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnlDaftarBelanjaLayout.setVerticalGroup(
            pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaftarBelanjaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDaftarBelanjaLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hitung)))
                    .addGroup(pnlDaftarBelanjaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDaftarBelanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlDaftarBelanja, "pnlDaftarBelanja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(995, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 228, Short.MAX_VALUE)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1220, 700));

        jPanel4.setBackground(new java.awt.Color(235, 16, 16));

        lblKasir.setBackground(new java.awt.Color(235, 16, 16));
        lblKasir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblKasir.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dftNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dftNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dftNamaActionPerformed

    private void dftKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dftKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dftKeteranganActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        // TODO add your handling code here:
        if(a==1){
                getkodepenjualan();
                //sudah mendapatkan kode penjualan
                
               String SQL = "Insert into tb_penjualan(kode_penjualan,kode_kasir,kode_pelanggan) values('"+kodepenjualan+"','"+kode+"','"+idpelanggan+"');";
               Koneksi.execute(SQL);
               System.out.println(kodepenjualan+"  "+kode+"  "+idpelanggan);
               System.out.println(kode);
               CardLayout clayout = (CardLayout) pnlUtama.getLayout();
               clayout.show(pnlUtama, "pnlBeli");
            
        }else{
            JOptionPane.showMessageDialog(this, " Silahkan daftar terlebih dahulu ", "PERHATIAN" ,JOptionPane.WARNING_MESSAGE);
        }a=0;
    }//GEN-LAST:event_btnMulaiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlBeli");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlDaftarBelanja");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        plg = new DefaultTableModel(null,kolom3);
        tblPlg.setModel(plg);
        String st = "select kode_pelanggan,nama_pelanggan,alamat from ms_pelanggan where nama_pelanggan like '%"+txtNama.getText()+"%';";
        try{
            ResultSet rs = Koneksi.executeQuery(st);
                
                while(rs.next()){
                    plg.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                    
                    
                    
                }
        }catch(SQLException ex){
             Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
         }
        tblPlg.setModel(plg);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlDaftar");
        
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnDaftar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftar2ActionPerformed
        // TODO add your handling code here:
        String sql = "select kode_pelanggan from ms_pelanggan order by kode_pelanggan desc limit 1;";
        
        try{
            ResultSet rs = Koneksi.executeQuery(sql);
             if(rs.next()){
                    idpelanggan = rs.getString(1);
                    int ID= Integer.parseInt(idpelanggan);
                     ID ++;
                     idpelanggan = String.valueOf(ID);
                }else{
                    idpelanggan="191116015";
                }
        }catch (SQLException ex){
             Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         if ("".equals(dftNama.getText()) || "".equals(dftTlf.getText()) ||
                "".equals(dftAlamat.getText())){
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            
            String SQL = "INSERT INTO ms_pelanggan "
                    + "VALUES ('"+idpelanggan+"','"+dftNama.getText()+"','"+dftTlf.getText()+"','"+dftAlamat.getText()+"')";
             int status = Koneksi.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "data berhasil ditambahkan ", "sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                        dftKeterangan.setText("Selamat datang " +dftNama.getText()+ " di TOKO BANGUNAN TUREN. id anda = ("+idpelanggan+")");
                        a=1;
            }else{
                JOptionPane.showMessageDialog(this, "data gagal ditambahkan ", "sukses",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDaftar2ActionPerformed

    private void btnOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeActionPerformed
        // TODO add your handling code here:
        if(a==1){
            
                getkodepenjualan();
                
                String insert = "insert into tb_penjualan (kode_penjualan,kode_pelanggan,kode_kasir) values ('" +kodepenjualan+"','"+idpelanggan+"','"+kode+"');";
                Koneksi.execute(insert);
                System.out.println(kodepenjualan+"  "+kode+"  "+idpelanggan);
                CardLayout clayout = (CardLayout) pnlUtama.getLayout();
                clayout.show(pnlUtama, "pnlBeli");
        }else{
            JOptionPane.showMessageDialog(this, " Silahkan daftar terlebih dahulu ", "PERHATIAN" ,JOptionPane.WARNING_MESSAGE);
        }a=0;
    }//GEN-LAST:event_btnOkeActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        // TODO add your handling code here:
        dft = new DefaultTableModel(null,kolom2);
        tblCari.setModel(dft);
        int no=1;
        String st = "select kode_barang, nama_barang, harga,satuan from ms_barang where nama_barang like '%"+txtBarang.getText()+"%';";
        ResultSet rs = Koneksi.executeQuery(st);
        
        try{while (rs.next()){
            dft.addRow(new Object[] {no++,rs.getString(2),rs.getString(3)});
            }
        }catch(SQLException ex){
             Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblCari.setModel(dft);
        
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    
     String nm=namabarang;
     String hrga= txtHarga.getText();
     String bnyk = txtJumlah.getText();
     int t = Integer.parseInt(txtHarga.getText()) * Integer.parseInt(txtJumlah.getText());
     String sql = "Insert into tb_detail_penjualan values ('"+kodepenjualan+"','"+kodebarang+"','"+txtHarga.getText()+"','"+txtJumlah.getText()+"','"+String.valueOf(t)+"');";
     Koneksi.execute(sql);
        System.out.println(kodepenjualan+"','"+kodebarang+"','"+txtHarga.getText()+"','"+txtJumlah.getText()+"','"+String.valueOf(t));
     String[] data={nm,hrga,bnyk};
     dtm.addRow(data);
     tblBarang.setModel(dtm);
     
     txtHarga.setText("");
     txtJumlah.setText("");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        int baris = tblBarang.getSelectedRow();
       
        
        String st = "select kode_barang, nama_barang, harga from ms_barang where nama_barang= '"+ tblBarang.getValueAt(baris, 0).toString() +"';";
       
            try{
            ResultSet rs = Koneksi.executeQuery(st);
            if(rs.next()){
               
                kodebarang=rs.getString(1);
               
            }else{
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan","Peringatan",JOptionPane.WARNING_MESSAGE);
            }
        
        }catch(SQLException ex){
             Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dlt = "delete from tb_detail_penjualan where kode_penjualan = '"+kodepenjualan+"' && kode_barang='"+kodebarang+"';";
        System.out.println(kodepenjualan + "   "+kodebarang);
        Koneksi.execute(dlt);
        dtm.removeRow(baris);
        tblBarang.setModel(dtm);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        if(tblBarang.getRowCount() != 0){
           if(txtNama.getText().length() != 0){
               labelnm.setText(lblNma.getText());
           }else{
               labelnm.setText(dftNama.getText());
           }
        labelid.setText(idpelanggan);
        String SQL = "SELECT * FROM tb_detail_penjualan where kode_penjualan='"+kodepenjualan+"';";
        ResultSet rs = Koneksi.executeQuery(SQL);
         int yt=0;
        try { while (rs.next()) {
           
            String w = tblBarang.getValueAt(yt, 0).toString();
            String s = rs.getString(3);
            String t =rs.getString(4);
            String k= rs.getString(5);
            String data[] = {w,s,t,k};
            yt++;
            dftr.addRow(data);
            }
         } catch (SQLException ex){
             Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
         }
        tblDaftar.setModel(dftr);
      
        String jum="select sum(total) from tb_detail_penjualan where kode_penjualan='"+ kodepenjualan+"';";
        
        try{
            ResultSet r=Koneksi.executeQuery(jum);
            if(r.next()){
                String jumlah=r.getString(1);
                int w=Integer.parseInt(jumlah);
              
                int t=w;
                jumlah= String.valueOf(t);
                txtTotal.setText(jumlah);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        yt=0;
        
            CardLayout clayout = (CardLayout) pnlUtama.getLayout();
            clayout.show(pnlUtama, "pnlDaftarBelanja");
        }else{
            JOptionPane.showMessageDialog(null, "Data belanja masih kosong");
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlPelanggan");
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int g=Integer.parseInt(txtTotal.getText());
        int r=Integer.parseInt(txtBay.getText());
        r=r-g;
        txtKembalian.setText(String.valueOf(r));
        kembali=String.valueOf(r);
    }//GEN-LAST:event_HitungActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlBeli");
        dftr = new DefaultTableModel(null,kolom1);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String sql="update tb_penjualan set total='"+txtTotal.getText()+"',bayar='"+txtBay.getText()+"' where kode_penjualan='"+kodepenjualan+"';";
        Koneksi.execute(sql);
       
        kosong();
         CardLayout clayout = (CardLayout) pnlUtama.getLayout();
        clayout.show(pnlUtama, "pnlPelanggan");
        try{
            Connection con=Koneksi.setKoneksi();
            
                try{
                    String report ="D:\\Turen_Indah_1 (3)\\Turen_Indah_1\\src\\report1.jrxml";                    
                    HashMap hs = new HashMap();
                    hs.put("kode",kodepenjualan);
                    hs.put("kembali",kembali);
                  
                    JasperReport jr = JasperCompileManager.compileReport(report);
                    JasperPrint jp = JasperFillManager.fillReport(jr, hs, con);
                    JasperViewer.viewReport(jp, false);
                }catch(Exception rptexcpt){
                    System.out.println("report gagal"+ rptexcpt.getMessage());
                }
        }catch(Exception e){
            System.out.println("koneksi gagal"+e.getMessage());
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void tblCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCariMouseClicked
        // TODO add your handling code here:
        int w = tblCari.getSelectedRow();
        String st = "select kode_barang, nama_barang, harga from ms_barang where nama_barang like '%"+tblCari.getValueAt(w, 1).toString()+"%';";
        ResultSet rs = Koneksi.executeQuery(st);
        try{
                if(rs.next()){
                String harga = rs.getString(3);
                namabarang= rs.getString(2);
                kodebarang=rs.getString(1);
                txtHarga.setText(harga);
            }else{
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan","Peringatan",JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(SQLException ex){
             Logger.getLogger(KasirMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblCariMouseClicked

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int w=tblBarang.getSelectedRow();
        
        lbln.setText(tblBarang.getValueAt(w, 0).toString());
        txtj.setText(tblBarang.getValueAt(w, 2).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sq="select kode_barang ,harga from ms_barang where nama_barang ='"+lbln.getText()+"';";
        int h=0;
        try{
            ResultSet r=Koneksi.executeQuery(sq);
           if(r.next()){ 
               kodebarang=r.getString(1);
               h=Integer.parseInt(r.getString(2));
           }
           
        }catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Terjadi kesalahan","Peringatan",JOptionPane.WARNING_MESSAGE);
        }
        h=h*Integer.valueOf(txtj.getText());
        String sql = "update tb_detail_penjualan set jumlah='"+txtj.getText()+"',total='"+String.valueOf(h) +"' where kode_penjualan='"+kodepenjualan+"' and kode_barang='"+kodebarang+"';";
        Koneksi.execute(sql);
        
        int q=tblBarang.getSelectedRow();
        tblBarang.setValueAt(txtj.getText(), q, 2);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlgMouseClicked
        // TODO add your handling code here:
        int ws= tblPlg.getSelectedRow();
        lblNma.setText(tblPlg.getValueAt(ws, 1).toString());
        lblPlg.setText(tblPlg.getValueAt(ws, 0).toString());
        a=1;
        idpelanggan=tblPlg.getValueAt(ws, 0).toString();
    }//GEN-LAST:event_tblPlgMouseClicked

    private void txtBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirMain("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnDaftar2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMulai;
    private javax.swing.JButton btnOke;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextArea dftAlamat;
    private javax.swing.JTextField dftKeterangan;
    private javax.swing.JTextField dftNama;
    private javax.swing.JTextField dftTlf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labelnm;
    private javax.swing.JLabel lblKasir;
    private javax.swing.JLabel lblNma;
    private javax.swing.JLabel lblPlg;
    private javax.swing.JLabel lbln;
    private javax.swing.JPanel pnlBeli;
    private javax.swing.JPanel pnlDaftar;
    private javax.swing.JPanel pnlDaftarBelanja;
    private javax.swing.JPanel pnlPelanggan;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblCari;
    private javax.swing.JTable tblDaftar;
    private javax.swing.JTable tblPlg;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtBay;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtj;
    // End of variables declaration//GEN-END:variables
}
